package day26;

import java.util.Set;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class GetMethods {

	public static void main(String[] args) throws InterruptedException {
	
		WebDriver driver=new ChromeDriver();
		
		//get()
		driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");	
		Thread.sleep(3000);
	
		//getTitle()
		//System.out.println("title of the page: "+driver.getTitle());
		
		//getCurrentUrl()
		//System.out.println("Curretn URL: "+ driver.getCurrentUrl());4u74
		
		//getPageSource()
		//System.out.println("Page Source................."+driver.getPageSource());
		
		
		//getWindowHandle()  - id is randomely generated by browser at run time.
		//System.out.println("Browser window ID:"+ driver.getWindowHandle()); 	//C8ACF295B1B0ACCF1383073E9DAC6A18
																				//554EA2975E59F425DE6B06044CE6FC52
		driver.findElement(By.linkText("OrangeHRM, Inc")).click(); //opens the another browser window/tab
		
		Set<String> windIds=driver.getWindowHandles();
		
		for(String winid:windIds)
		{
			System.out.println(winid);
		}
	
	}
}
